### ISSUE TITLE
USER STORY: Wordnest home page

### ISSUE THREAD

**Issue by Dima-Bulavenko** [Dima-Bulavenko/wordnest#10]
As a **user**, I want **a home page**, so that **I have quick access to all the site's options**.

## Acceptance criteria
1. Must have link to user account in the header of the page.
2. Must show all words displayed in order of their addition date, from newest to oldest.
3. The header must include a burger menu containing a list of all named sets of words associated with the dictionary, along with a button for adding a new set.

## Tasks
- [x] Create base.html django template common for all pages of the application.
- [x] Create index.html. This is going to be the home page.
- [x] Add styles for the home page.
- [x] Create django view of the page.
