### ISSUE TITLE
USER STORY: Welcome page

### ISSUE THREAD

**Issue by Dima-Bulavenko** [Dima-Bulavenko/wordnest#11]
As a **user** I want **to see a welcome page when I visit the site first** so that **to get overview what this site is for and what features it has**.

## Acceptance criteria
1. Must have short description of the site.
2. Must have a sugestion to "sign in" or "sign up".
3. Must have a list of features that the site has.

## Tasks
- [ ] Create django view.
- [ ] Create template of the page that based on the "base.html" template. 
- [ ] Add styles for the template.
- [ ] Make testing of the written code.
