### ISSUE TITLE
USER STORY: Reset password

### ISSUE THREAD

**Issue by Dima-Bulavenko** [Dima-Bulavenko/wordnest#16]
As a **User** I want **to have ability to reset my password if I forgot one** so that **to restore access to my account**.

## Acceptance criteria
1. Must have form with email field which a user can fill up with the user's account email.
2. Must have the submit button to send this form.
3. Must have a inform page to tell the user check his email.
4. Must send an email with a link for password reset.
5. By following the link the user must get new form with two passwords fields, where the user should input new password.
6. The second form must have a submit button for sending the form to process it

## Tasks
- [ ] Create first form
- [ ] Create the inform page 
- [ ] Create the email structure to send it to user
- [ ] Creaet the second form to type new password
