### ISSUE TITLE
USER STORY: User registration

### ISSUE THREAD

**Issue by Dima-Bulavenko** [Dima-Bulavenko/wordnest#4]
As a **user** I can **create my own account** in oreder to  **create my dictionary and group words by different themes**.

## Acceptance criteria
1. The option should be provided by filling a registration form
2. The form must contain email, password and confirm password fields.
3. The form must validate when the user submit one.
4. If nessasary field should have a tooltip indicating which symbols and formats are valid for that field.
5. After submitting the form, the user must receive an email with a link to activate their account.
6. After the user clicks the link, they should be redirected to the home page and automatically logged in.

## Tasks
- [ ] Create wireframe of the registration page.
- [ ] Create HTML of  the page.
- [ ] Create CSS for the page.
- [ ] Create view to process the page.
- [ ] Create the logic for sending the email with activation link.
