### ISSUE TITLE
USER STORY: User login 

### ISSUE THREAD

**Issue by Dima-Bulavenko** [Dima-Bulavenko/wordnest#5]
As a **user** I want to **sing in to my account** in order to **get access to my account and to my dictionaries**.

## Acceptance criteria
1. This feature should be provided by filling the login form.
2. The form must have email, password fields and remember me checkbox.
3. After submitting the form user should be redirected to the main page.

## Tasks
- [ ] Create HTML for login page.
- [ ] Create CSS for login page.
- [ ] Create view for processing the page and the form data.
