### ISSUE TITLE
USER STORY: Create multiple dictionaries

### ISSUE THREAD

**Issue by Dima-Bulavenko** [Dima-Bulavenko/wordnest#8]
As a **user**, I want **to create multiple dictionaries** so that **I can learn multiple lenguages simultaniously**.

## Acceptance criteria
1. Implament this option on the home page and in the user account settings.
2. To create the dictionary user should hit "Add dictionary" button.
3 . After clicking the button, a form should appear with fields for selecting the first language and the second one, along with a 'Create Dictionary' button.
4. When the form appears, other content on the page should be inaccessible until the user either clicks the 'Create Dictionary' button or the 'Close Form' icon.
5. User isn't allowed create the same sets of language.

## Tasks
- [ ] Create HTML for the form.
- [ ] Create CSS for the form.
- [ ] Implement JS to show the form.
- [ ] Implement sending form data to the server using AJAX to avoid page reloading.
- [ ] Implement creating a new dictionary on the server side and sending a response to the client side.
- [ ] Update the list of user's dictionaries on the client side.
