### ISSUE TITLE
USER STORY: Word translating

### ISSUE THREAD

**Issue by Dima-Bulavenko** [Dima-Bulavenko/wordnest#9]
As a **user**, I want to **translate words from one language to another and vice versa** so that **I can add word pairs to my dictionary**.

## Acceptance criteria
1. Input field to enter a word.
2. if the word is already in the user's dictionary, show it below the input field.
3. If the word is not in the dictionary, translate it by pressing the "Enter" key or clicking on the translate button next to the input field.
4. Users can translate both single words and sentences.
5. The user should receive multiple translations of the word if they exist.

## Tasks
- [x] Add HTML and CSS for the feature.
- [ ] Implement AJAX request to search the word in user's dictionary.
- [x] Implement AJAX request to the API to get the translations of the word
